### PR TITLE
Added changes for ghostscript upgrade to version 10.03.1

### PR DESCRIPTION
**Pull request by nurkudeIDBS**
Added changes for gostscript upgrade to version 10.03.1

### CODE REVIEW

**Review by mwinkworthIDBS — APPROVED** [review]
LGTM

**Comment by kdaviesIDBS** [comment]
seems to be using a mixture of "IDBS Cloud" and "IDBS Web" as replacements,  does it matter?

**Comment by kdaviesIDBS** [comment]
I have a question about whether the licensing commitment been re-checked for this upgrade?  I cannot remember off the top of my head if IDBS have a commercial license already.

**Comment by nurkudeIDBS** [comment]
> I have a question about whether the licensing commitment been re-checked for this upgrade? I cannot remember off the top of my head if IDBS have a commercial license already.

I have checked page https://idbs-hub.atlassian.net/wiki/spaces/PD/pages/4043571276/Deprecated+Commercial+Third+Party+Software+Listing+New and didn't found anything for Ghostscript

**Comment by kdaviesIDBS** [comment]
Update: I answered my own question. We use AGPL license not commercial license - As a condition of this IDBS make the source code public available.

**Review by kdaviesIDBS — APPROVED** [review]
LGTM - thanks for addressing this.

**Pull request merged**
